# This version of config.mk was generated by:
# ../src/configure
# Any changes made here will be lost if configure is re-run
ARCH = x86_64
SUBARCH = 
ASMSUBARCH = 
srcdir = ../src
prefix = /dev/null
libdir = $(prefix)/lib
includedir = $(prefix)/include
CC = clang
CFLAGS = 
CFLAGS_AUTO = -pipe -fomit-frame-pointer -fno-unwind-tables -fno-asynchronous-unwind-tables -ffunction-sections -fdata-sections -Werror=implicit-function-declaration -Werror=implicit-int -Werror=pointer-sign -Werror=pointer-arith -Qunused-arguments
CFLAGS_AUTO += -O0 -g
CFLAGS_C99FSE = -nostdinc -ffreestanding -Wa,--noexecstack
CFLAGS_MEMOPS = 
CPPFLAGS = 
LDFLAGS = 
LDFLAGS_AUTO = -Wl,--sort-section,alignment -Wl,--sort-common -Wl,--gc-sections -Wl,--hash-style=both -Wl,--no-undefined -Wl,--exclude-libs=ALL -Wl,-Bsymbolic-functions
CROSS_COMPILE = 
ADD_CFI = no
