# This version of config.mk was generated by:
# ./configure --prefix=/home/nick/dev/sl
# Any changes made here will be lost if configure is re-run
ARCH = x86_64
SUBARCH = 
ASMSUBARCH = 
srcdir = .
prefix = /home/nick/dev/sl
libdir = $(prefix)/lib
includedir = $(prefix)/include
CC = clang
CFLAGS = 
CFLAGS_AUTO = -Os -pipe -fomit-frame-pointer -fno-unwind-tables -fno-asynchronous-unwind-tables -ffunction-sections -fdata-sections -Werror=implicit-function-declaration -Werror=implicit-int -Werror=pointer-sign -Werror=pointer-arith -Qunused-arguments
CFLAGS_C99FSE = -nostdinc -ffreestanding -Wa,--noexecstack
CFLAGS_MEMOPS = 
CFLAGS_NOSSP = -fno-stack-protector
CPPFLAGS = 
LDFLAGS = 
LDFLAGS_AUTO = -Wl,--sort-section,alignment -Wl,--sort-common -Wl,--gc-sections -Wl,--hash-style=both -Wl,--no-undefined -Wl,--exclude-libs=ALL -Wl,-Bsymbolic-functions
CROSS_COMPILE = 
LIBCC = 
OPTIMIZE_GLOBS = internal/*.c malloc/*.c string/*.c
ALL_TOOLS = 
TOOL_LIBS = 
ADD_CFI = no
WRAPCC_CLANG = $(CC)
